config/routes.rb
TimetableApp::Application.routes.draw do
  
  resources :timetables do
    member do
	  get 'detail'
	end
  end
  resources :slots

  root 'timetables#index'
  

end

app/models/slot.rb
class Slot < ActiveRecord::Base
  validates :title, :timetable_id, presence: true
  
  belongs_to :timetable
end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
  validates :name, :slot_unit_size, presence: true

  has_many :slots, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :set_slot, only: [:show, :edit, :update, :destroy]

  # GET /slots
  # GET /slots.json
  def index
    @slots = Slot.all
  end

  # GET /slots/1
  # GET /slots/1.json
  def show
  end

  # GET /slots/new
  def new
    @timetable = Timetable.find(session[:current_timetable])
    @slot = @timetable.slots.build
  end

  # GET /slots/1/edit
  def edit
  end

  # POST /slots
  # POST /slots.json
  def create
    @timetable = Timetable.find(session[:current_timetable])
	@slot = @timetable.slots.build(slot_params)
	
      respond_to do |format|
        if @slot.save
          format.html { redirect_to @slot, notice: 'Slot was successfully created.' }
          format.json { render action: 'show', status: :created, location: @slot }
        else
          format.html { render action: 'new' }
          format.json { render json: @slot.errors, status: :unprocessable_entity }
      	  end
      end
	
  end

  # PATCH/PUT /slots/1
  # PATCH/PUT /slots/1.json
  def update
    respond_to do |format|
      if @slot.update(slot_params)
        format.html { redirect_to @slot, notice: 'Slot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1
  # DELETE /slots/1.json
  def destroy
    @slot.destroy
    respond_to do |format|
      format.html { redirect_to slots_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slot
      @slot = Slot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slot_params
      params.require(:slot).permit(:title, :description, :start_time, :end_time)
    end
end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
  before_action :set_timetable, only: [:show, :edit, :update, :destroy, :detail]

  # GET /timetables
  # GET /timetables.json
  def index
    @timetables = Timetable.all
  end

  # GET /timetables/1
  # GET /timetables/1.json
  def show
  end

  # GET /timetables/new
  def new
    @timetable = Timetable.new
  end

  # GET /timetables/1/edit
  def edit
  end

  # POST /timetables
  # POST /timetables.json
  def create
    @timetable = Timetable.new(timetable_params)

    respond_to do |format|
      if @timetable.save
        format.html { redirect_to @timetable, notice: 'Timetable was successfully created.' }
        format.json { render action: 'show', status: :created, location: @timetable }
      else
        format.html { render action: 'new' }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timetables/1
  # PATCH/PUT /timetables/1.json
  def update
    respond_to do |format|
      if @timetable.update(timetable_params)
        format.html { redirect_to @timetable, notice: 'Timetable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timetables/1
  # DELETE /timetables/1.json
  def destroy
    @timetable.destroy
    respond_to do |format|
      format.html { redirect_to timetables_url }
      format.json { head :no_content }
    end
  end

  # GET
  def detail
    
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timetable
      @timetable = Timetable.find(params[:id])
	  session[:current_timetable] = params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timetable_params
      params.require(:timetable).permit(:name, :start_day_weekly, :slot_unit_size, :day_start_time, :day_end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimetableApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/slots/_form.html.erb
<%= form_for @slot do |f| %>
  <% if @slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
      <% @slot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.time_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slots/edit.html.erb
<h1>Editing slot</h1>

<%= render 'form' %>

<%= link_to 'Show', @slot %> |
<%= link_to 'Back', slots_path %>

app/views/slots/index.html.erb
<div class="container">
<h1>Listing slots</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Timetable id</th>
      <th></th>
      <th></th>
	  <th></th>
    </tr>
  </thead>

  <tbody>
    <% @slots.each do |slot| %>
      <tr>
        <td><%= slot.title %></td>
        <td><%= slot.description %></td>
        <td><%= slot.start_time %></td>
        <td><%= slot.end_time %></td>
		<td><%= slot.timetable_id %></td>
        <td><%= link_to 'Show', slot %></td>
        <td><%= link_to 'Edit', edit_slot_path(slot) %></td>
        <td><%= link_to 'Destroy', slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Slot', new_slot_path %>
</div>

app/views/slots/new.html.erb
<div class="container">
<h1>New slot</h1>
<pre>
<%= @timetable.inspect %>
<%= @slot.inspect %>
</pre>
<%= render 'form' %>

<%#= link_to 'Back', timetable_path(@timetable) %>
</div>

app/views/slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @slot.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @slot.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @slot.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @slot.end_time %>
</p>

<p>
  <strong>Timetable:</strong>
  <%= @slot.timetable_id %>
</p>

<%= link_to 'Edit', edit_slot_path(@slot) %> |
<%= link_to 'Back', slots_path %>

app/views/timetables/_form.html.erb
<%= form_for(@timetable) do |f| %>
  <% if @timetable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timetable.errors.count, "error") %> prohibited this timetable from being saved:</h2>

      <ul>
      <% @timetable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'Week starts from Monday (untick means Sunday)' %><br>
    <%= f.check_box :start_day_weekly %>
  </div>
  <div class="field">
    <%= f.label :slot_unit_size %><br>
    <%= f.number_field :slot_unit_size %>
  </div>
  <div class="field">
    <%= f.label :day_start_time %><br>
    <%= f.time_select :day_start_time %>
  </div>
  <div class="field">
    <%= f.label :day_end_time %><br>
    <%= f.time_select :day_end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timetables/detail.html.erb
<div id="detail" class="container">
<p>
<h1><%= @timetable.name %></h1>

<%= link_to 'Add slot', new_slot_path, class: "btn btn-info pull-right" %>
</p>

<table class="table table-bordered">
<tr>
<th></th>
<% if @timetable.start_day_weekly %>
	<% (0..6).each do |i| %>
		<th><%= Date::DAYNAMES[(i+1)%7] %></th>
	<% end %>
<% else %>
	<% (0..6).each do |i| %>
		<th><%= Date::DAYNAMES[i] %></th>
	<% end %>
<% end %>
</tr>
<% $currT = @timetable.day_start_time 
   $unit = (@timetable.slot_unit_size*60)%>
<% until ($currT + $unit) > @timetable.day_end_time %>
  <tr><td><%= $currT.to_s(:time) + ' ~ '%>
          <%= ($currT + $unit).to_s(:time) %>
          </td>
  <% (0..6).each do |i| %>
    <td></td>
  <% end %>
  </tr>
<% $currT += $unit %>
<% end %>
</table>
<%= link_to 'Back', timetables_path %>
</div>

app/views/timetables/edit.html.erb
<div class="container">
<h1>Editing timetable</h1>

<%= render 'form' %>

<%= link_to 'Show', @timetable %> |
<%= link_to 'Back', timetables_path %>
</div>

app/views/timetables/index.html.erb
<div class="container">
<h1>Listing timetables</h1>

<div class="table-responsive">
<table class="table table-hover ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Week start from Monday</th>
      <th>Slot unit size</th>
      <th>Day start time</th>
      <th>Day end time</th>
      <th></th>
      <th></th>
      <th></th>
	  <th></th>
    </tr>
  </thead>

  <tbody>
    <% @timetables.each do |timetable| %>
      <tr>
        <td><%= timetable.name %></td>
        <td><%= timetable.start_day_weekly %></td>
        <td><%= timetable.slot_unit_size %></td>
        <td><%= timetable.day_start_time.to_s(:time) %></td>
        <td><%= timetable.day_end_time.to_s(:time) %></td>
        <td><%= link_to 'Show', timetable , class: "btn btn-info"%></td>
		<td><%= link_to 'Detail', detail_timetable_path(timetable) , class: "btn btn-success"%></td>
        <td><%= link_to 'Edit', edit_timetable_path(timetable) , class: "btn btn-warning"%></td>
        <td><%= link_to 'Delete', timetable, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Timetable', new_timetable_path , class: "btn btn-primary"%>
</div>

app/views/timetables/new.html.erb
<div class="container">
<h1>New timetable</h1>

<%= render 'form' %>

<%= link_to 'Back', timetables_path %>
</div>

app/views/timetables/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @timetable.name %>
</p>

<p>
  <strong>Start day weekly:</strong>
  <%= @timetable.start_day_weekly %>
</p>

<p>
  <strong>Slot unit size:</strong>
  <%= @timetable.slot_unit_size %>
</p>

<p>
  <strong>Day start time:</strong>
  <%= @timetable.day_start_time.to_s(:time) %>
</p>

<p>
  <strong>Day end time:</strong>
  <%= @timetable.day_end_time.to_s(:time) %>
</p>

<%= link_to 'Edit', edit_timetable_path(@timetable) %> |
<%= link_to 'Back', timetables_path %>
</div>